// Generated by Gemini (gemini-3.5-flash), fact-checked; edits are listed in
// docs/verkiesing/ui-kopie-wysigings.md. Values are copied verbatim from
// docs/verkiesing/ui-kopie.json — do not hand-write Afrikaans here.
export const KOPIE = {
  ovk_etiket: "KONTAK DIE OVK",
  ovk_opskrif: "Vind vinnig uit of jy geregistreer is",
  ovk_inleiding: "Jy kan net stem waar jy geregistreer is, so maak nou seker en kies een van die maniere hieronder.",
  whatsapp_etiket: "WHATSAPP",
  whatsapp_titel: "Stuur \"Hi\" vir die OVK",
  whatsapp_knoppie: "Maak WhatsApp oop",
  sms_etiket: "SMS",
  sms_titel: "SMS jou ID-nommer na",
  sms_nota: "Jy kry jou registrasiestatus per SMS terug.",
  sms_knoppie: "Stuur nou SMS",
  aanlyn_etiket: "AANLYN",
  aanlyn_titel: "Sleutel jou ID in op die OVK se \"Voter Information\"-blad",
  aanlyn_nota: "Dit wys jou status, stemlokaal en wyk.",
  aanlyn_knoppie: "Gaan na blad",
  bel_etiket: "OPROEP",
  bel_titel: "Die OVK-hulplyn",
  bel_nota: "Weeksdae 08:00 tot 17:00",
  bel_knoppie: "Skakel nou",
  id_etiket: "WAT OM SAAM TE BRING",
  id_slimkaart: "Slimkaart-ID",
  id_boekie: "Groen ID-boekie",
  id_nota: "Geen ander dokument word aanvaar nie, ook nie 'n rybewys of paspoort nie.",
  spesiaal_etiket: "SPESIALE STEM",
  spesiaal_titel: "Kan jy nie op 4 November stem nie?",
  spesiaal_teks: "SMS jou ID-nommer na 32249 (R1,50 per SMS) – slegs vir 'n besoek aan jou eie stemlokaal op 2 of 3 November.",
  spesiaal_knoppie_toe: "Aansoeke open 21 September",
  spesiaal_knoppie_oop: "Doen aansoek per SMS",
  spesiaal_knoppie_verby: "Aansoeke het reeds gesluit",
  onthou_etiket: "ONTHOU",
  onthou_titel: "Jy stem net waar jy geregistreer is",
  onthou_teks: "In plaaslike verkiesings kan jy nie by 'n ander stemlokaal stem nie; die kieserslys het op 7 Augustus gesluit.",
  held_etiket: "Plaaslike verkiesing · Woensdag 4 November 2026",
  held_boks_etiket: "BEVESTIG JOU STATUS",
  held_boks_titel: "Kyk of jy geregistreer is en waar jy stem",
  held_boks_skakel: "Sien meer",
  // --- Wyk-soeker (Gemini, Fase 2b) ---------------------------------
  // Placeholders are substituted by the component and MUST survive a rewrite. What each
  // one means is per slot:
  //   soek_resultate_telling      {n} = how many results, {q} = the reader's search term
  //   soek_resultate_telling_een  {q} = the reader's search term (the singular of the above)
  //   soek_wyk_nommer             {n} = the ward number
  //   soek_wyk_aantal             {n} = how many wards the place spans
  //   soek_wyke_kies              {n} = how many wards, {q} = the MATCHED PLACE's name
  //                               (not what the reader typed)
  //   soek_geen                   {q} = the reader's search term
  // The three notice slots below carry two lines separated by "\n": the first line is the
  // statement, the second the advice. Keep the newline when rewriting.
  nav_vind_wyk: "Vind jou wyk",
  soek_etiket: "VIND JOU WYK",
  soek_titel: "Vind jou wyk, stemlokaal en kandidate",
  soek_plekhouer: "Voorstad, dorp of stemlokaal",
  soek_ligging_knoppie: "Gebruik my ligging",
  soek_ligging_besig: "Soek jou ligging…",
  soek_groep_plekke: "Plekke",
  soek_groep_stemlokale: "Stemlokale",
  soek_resultate_telling: "{n} resultate vir “{q}”",
  soek_resultate_telling_een: "1 resultaat vir “{q}”",
  soek_wyk_nommer: "Wyk {n}",
  soek_wyk_aantal: "{n} wyke",
  soek_wyke_kies: "{q} val oor {n} wyke. Kies joune:",
  soek_geen: "Niks gevind vir “{q}” nie.\nProbeer die naam van jou stemlokaal of gebruik jou ligging.",
  soek_ligging_geweier: "Ons kon nie jou ligging kry nie.\nTik eerder jou voorstad, dorp of stemlokaal.",
  soek_ligging_buite:
    "Jou ligging val nie binne 'n wyk nie.\nDit gebeur naby die see of op die rand van 'n wyk. Soek eerder op jou stemlokaal.",
  soek_registrasie_skakel: "Is jy geregistreer?",
  watkom_opskrif: "BELANGRIKE DATUMS",
  mylpaal_kandidaatlyste: "16 September: Die finale kandidaatlyste word gepubliseer.",
  mylpaal_spesiaal_aansoek: "21 September tot 12 Oktober (17:00): Doen aansoek vir 'n spesiale stem.",
  mylpaal_trekking: "23 September: Die trekking bepaal die volgorde van partye op die stembriewe.",
  mylpaal_spesiale_stemme: "2 en 3 November: Spesiale stemme, 08:00 tot 17:00.",
  mylpaal_stemdag: "4 November: Verkiesingsdag, stemlokale oop van 07:00 tot 21:00.",
  program_ondertitel: "Die program is elke Vrydag regstreeks",
  stroom_opskrif: "WAT ANDER BERIG",
  stroom_onderskrif: "Opskrifte presies soos gepubliseer, met skakels na die oorspronklike berigte.",
  stroom_meer: "Wys nog berigte",
  stroom_minder: "Wys minder berigte",
  stroom_lees_by: "Lees by",
  stroom_leeg: "Geen berigte tans beskikbaar nie",
  terugvoer_vraag: "Het jy gekry wat jy gesoek het?",
  terugvoer_ja: "Ja",
  terugvoer_nee: "Nee",
  terugvoer_dankie: "Dankie, dit help ons om die blad te verbeter.",
  // --- Wykblad (Gemini, Fase 2b) ------------------------------------
  // Placeholders are substituted by the components and MUST survive a rewrite:
  //   {w} = the ward number        {n} = a count        {m} = a total
  //   {q} = a name (municipality, district, or an already-formatted date)
  // Per slot:
  //   wyk_bladtitel / wyk_beskrywing   {w} = ward number, {q} = municipality name
  //   wyk_stemlokale_opskrif           {n} = how many stations, {w} = ward number
  //   wyk_stemlokale_opskrif_een       {w} = ward number (the singular of the above)
  //   stembrief_teller                 {n} = which ballot, {m} = how many ballots
  //   stembrief_wyk_uitleg             {w} = ward number
  //   stembrief_pv / stembrief_distrik {q} = the council's name
  //   laas_bygewerk                    {q} = the source date, already in Afrikaans
  //   og_wyk_sjabloon                  {n} = how many ward candidates
  // wyk_raadslid_teks was fact-checked against the Municipal Structures Act (s73: the ward
  // councillor chairs the ward committee).
  wyk_kruimel_tuis: "Verkiesing 2026",
  wyk_bladtitel: "Wyk {w} · {q} — Verkiesing 2026",
  wyk_beskrywing:
    "Jou stembriewe, kandidate en stemlokale vir wyk {w} in {q} vir die plaaslike verkiesing op 4 November 2026.",
  wyk_raadslid_opskrif: "Wat doen 'n wyksraadslid?",
  wyk_raadslid_teks:
    "'n Wyksraadslid word deur die kiesers van een wyk verkies om hulle in die raad te verteenwoordig. Dié raadslid lei ook die wykkomitee wat die gemeenskap se sienings na die raad bring.",
  wyk_stemlokale_opskrif: "{n} stemlokale in wyk {w}",
  wyk_stemlokale_opskrif_een: "1 stemlokaal in wyk {w}",
  wyk_stemlokale_nota: "Jy mag net stem by die stemlokaal waar jy geregistreer is.",
  wyk_stemlokale_geen: "Daar is nog geen stemlokale vir hierdie wyk om te wys nie.",
  wyk_stembriewe_opskrif: "Jou stembriewe",
  stembrief_teller: "Stembrief {n} van {m}",
  stembrief_wyk: "Wykstembrief",
  stembrief_wyk_uitleg: "Hiermee kies jy een kandidaat as wyksraadslid vir wyk {w}.",
  stembrief_pv: "Stembrief vir die {q}-raad",
  stembrief_pv_uitleg: "Jy stem vir 'n party en die setels word uit die partye se lyste gevul.",
  stembrief_distrik: "Stembrief vir die {q}-distriksraad",
  stembrief_distrik_uitleg: "Jy stem vir 'n party in die distriksraad.",
  volgorde_alfabeties: "Alfabeties",
  volgorde_stembrief: "Volgorde soos op die stembrief",
  onafhanklik: "Onafhanklik",
  // A ballot line the OVK published without a name (Piet, 2026-09-16: keep the line).
  kandidaat_sonder_naam: "Naam nie op die amptelike OVK-lys nie",
  wys_lys: "Wys lys",
  versteek_lys: "Versteek lys",
  kandidate_nog_nie_gelaai:
    "Daar is nog geen kandidate vir hierdie stembrief nie.",
  laas_bygewerk: "Laas bygewerk: {q}",
  bron_ovk:
    "Bron: OVK (IEC) · Munisipale Afbakeningsraad · Statistiek Suid-Afrika, Sensus 2011 (eie verwerking)",
  bron_ovk_skakel: "Sien die OVK se lys",
  og_wyk_sjabloon: "{n} kandidate · Stem op 4 November",
  og_wyk_geen: "Stem op 4 November",
  // Fix round 1. og_masthead is the share card's own masthead line — its own slot, so a
  // rewrite of the breadcrumb's "Verkiesing 2026" can never change the card. og_wyk_alt is
  // the card's alt text and must stay generic: Next only allows a static `alt` export, so
  // it cannot name a ward. bron_nota_setels_2021 is passed in by the municipality page;
  // the ward page leaves the note unset.
  og_masthead: "Verkiesing 2026",
  og_wyk_alt: "Nuuspod se wykblad vir die plaaslike verkiesing op 4 November 2026",
  kruimelspoor_etiket: "Kruimelspoor",
  bron_nota_setels_2021: "Setelberekening 2021 volgens die OVK se amptelike uitslae",
  // --- Munisipaliteitsblad (Gemini, Fase 2b) ------------------------
  // Placeholders are substituted by the components and MUST survive a rewrite:
  //   muni_bladtitel / muni_beskrywing      {q} = the municipality's display name
  //   muni_onderskrif_distrik               {q} = the district's name
  //   muni_wyke_aantal                      {n} = how many wards
  //   muni_wyke_aantal_een                  (the singular of the above, no placeholder)
  //   muni_2021_raadsgrootte                {n} = the full 2021 council size
  //   muni_2021_wys_sonder_setels           {n} = how many parties hold 0 seats
  // The ward links in the grid reuse `soek_wyk_nommer` ("Wyk {n}"), so the two pages can
  // never disagree about what a ward is called.
  //
  // muni_geen_wyke is shown on a district council, which has no wards of its own. It is
  // deliberately one plain sentence: anything about how a district council's seats are
  // actually filled is a legal claim and needs fact-checking first (Task 9).
  muni_tipe_plaaslik: "Plaaslike munisipaliteit",
  muni_tipe_metro: "Metro",
  muni_tipe_distrik: "Distriksraad",
  muni_bladtitel: "{q} — Verkiesing 2026",
  muni_beskrywing:
    "Die wyke van {q}, die partye op die stembrief en hoe die raad ná 2021 gelyk het — vir die plaaslike verkiesing op 4 November 2026.",
  muni_onderskrif_distrik: "{q}-distrik",
  muni_wyke_aantal: "{n} wyke",
  muni_wyke_aantal_een: "1 wyk",
  muni_wyke_opskrif: "Wyke",
  muni_geen_wyke: "Hierdie raad het nie sy eie wyke nie.",
  muni_partye_opskrif: "Partye op die stembrief",
  muni_partye_nog_nie_gelaai:
    "Daar is nog geen partye vir hierdie munisipaliteit nie.",
  muni_2021_opskrif: "Raad ná 2021 (amptelik)",
  muni_2021_raadsgrootte: "{n} setels",
  muni_2021_geen_meerderheid:
    "Geen party het ná die 2021-verkiesing 'n meerderheid in hierdie raad gehad nie.",
  muni_2021_kolom_party: "Party",
  muni_2021_kolom_wyk: "Wyksetels",
  muni_2021_kolom_pv: "PV-setels",
  muni_2021_kolom_totaal: "Totaal",
  muni_2021_onafhanklikes: "Onafhanklike raadslede",
  // Screen-reader text for the two cells of the independents row that hold a dash: the
  // ward/PR split of independent seats is in no database row, so the cell states that
  // rather than being hidden, which would leave the row with two cells instead of four.
  muni_2021_geen_data: "Geen data",
  muni_2021_wys_sonder_setels: "Wys ook partye sonder setels ({n})",
  muni_2021_versteek_sonder_setels: "Versteek partye sonder setels",
  muni_2021_sortering: "Gesorteer op partynaam",
  // --- Wykuitslag 2021 (Gemini) --------------------------------------------
  // uitslag2021_hernommer {n} = the 2021 ward number. The "verander" pair is shown on a ward
  // whose voting districts differ from every 2021 ward; the link goes to the municipality page.
  uitslag2021_opskrif: "WYKUITSLAG 2021",
  uitslag2021_onderskrif: "Die OVK se amptelike uitslag van die wykstembrief in 2021. Hierdie wyk bestaan uit presies dieselfde stemdistrikte as toe.",
  uitslag2021_hernommer: "In 2021 was hierdie selfde gebied wyk {n}.",
  uitslag2021_kolom_party: "Party",
  uitslag2021_kolom_stemme: "Stemme",
  uitslag2021_kolom_persent: "%",
  uitslag2021_onafhanklik: "Onafhanklike kandidaat of kandidate",
  uitslag2021_geregistreer: "Geregistreerde kiesers",
  uitslag2021_stemdeelname: "Stemdeelname",
  uitslag2021_bedorwe: "Bedorwe stemme",
  uitslag2021_verander: "Hierdie wyk se grense het sedert 2021 verander, daarom pas geen 2021-wykuitslag presies nie.",
  uitslag2021_verander_skakel: "Sien die raad se amptelike uitslag van 2021",
  uitslag2021_wys_klein: "Wys ook partye met minder as 1% ({n})",
  uitslag2021_versteek_klein: "Versteek partye met minder as 1%",
  uitslag2021_bron: "Bron: OVK se amptelike uitslae per stemdistrik van 2021, opgetel vir hierdie wyk.",
  // --- Plaaslike nuus (Gemini) --------------------------------------------
  // Placeholders: plaaslik_dorp {q} = a town name; plaaslik_munisipaliteit and
  // plaaslik_muni_opskrif {q} = the municipality's display name.
  plaaslik_opskrif: "PLAASLIKE NUUS",
  plaaslik_onderskrif: "Nuusopskrifte presies soos plaaslike koerante dit gepubliseer het, met skakels na die oorspronklike berigte.",
  plaaslik_omgewing: "Uit jou omgewing",
  plaaslik_dorp: "In {q}",
  plaaslik_munisipaliteit: "Nuus oor {q}",
  plaaslik_muni_opskrif: "Plaaslike nuus uit {q}",
  // --- Bladsy nie gevind nie (Gemini, Fase 2b) ----------------------
  nie_gevind_titel: "Bladsy nie gevind nie — Verkiesing 2026",
  nie_gevind_opskrif: "Bladsy nie gevind nie",
  nie_gevind_teks:
    "Hierdie bladsy bestaan nie, of die wyk- of munisipaliteitskode in die adres is verkeerd.",
  nie_gevind_tuis: "Terug na die tuisblad",
  nie_gevind_soek: "Soek jou wyk",
  voet_bron: "Bron van verkiesingsinligting: OVK (IEC)",
  voet_onafhanklik: "Nuuspod is nie aan die OVK of enige party verbonde nie.",
  voet_real411_vraag: "Sien jy vals verkiesingsinligting?",
  voet_real411_skakel: "Meld dit aan by Real411",
} as const;
